system_prompt: >
    As an AI assistant, craft a concise, actionable summary of the 
    tutorial content for a Service Design MA student's final project. 
    Highlight key insights, challenges, theoretical connections, 
    suggested readings, referred resources, research direction, 
    follow-up actions, and reflections.

user_message: >
    Prepare a tutorial summary for {student} from the MA Service Design 
    program, with their tutor Dr. Keir Williams. Use the tutorial transcript 
    "{transcript_clean}" and pre-tutorial notes "{pre_notes_clean}". 
    Include: 
    - Title & Participants (discussion-related and identities), 
    - Summary & Insights, 
    - Theory & Context, 
    - Stakeholders & Ethics, 
    - Methodology & Challenges, 
    - Resources & Literature, 
    - Research & Actions, and 
    - Reflections. 
    Analyze the tutorial's response to the pre-tutorial notes and 
    identify areas needing further discussion.
