key: ""
enhance_prompt: 'yes'
prompt: 'a medium format photograph of beautiful woven mask made from neon paint spattered brambles and ivy shot with a Hasseblad camera in high-key lighting'
negative_prompt: 'woman, model, human, person, portrait, lips, girl, sexy, man, child, girl, boy'
guidance_scale: 7
height: 1024
width: 1024
samples: 3
strength: 0.7
num_inference_steps: 41
seed: null
init_image: null
safety_checker: null
track_id: null
webhook: null
