call: "img2img"
init_image:
  - "/content/drive/MyDrive/unstable/images/masks/otter/Otter_clean_1.png"
  - "/content/drive/MyDrive/unstable/images/masks/otter/Otter_clean_2.png"
  - "/content/drive/MyDrive/unstable/images/masks/otter/Otter_clean_3.png"
  - "/content/drive/MyDrive/unstable/images/masks/otter/Otter_clean_4.png"
  - "/content/drive/MyDrive/unstable/images/masks/otter/Otter_clean_5.png"
  - "/content/drive/MyDrive/unstable/images/masks/otter/Otter_clean_6.png"
  - "/content/drive/MyDrive/unstable/images/masks/otter/Otter_clean_7.png"

prompt:
  - " An award winning portrait of an otters face shot with a Hasselblad medium format camera in high-key lighting"
negative_prompt: 
  - "human, extra features, man, woman, child, girl, boy, model"
seed: ""
strength: "0.8"
stable_guidance_scale: "8"
height: "1024"
width: "1024"
samples: "1"
num_inference_steps: "41"
enhance_prompt: "yes"
self_attention: "yes"
upscale: "yes"
